### ISSUE TITLE
Active tab appearance KO in Nav light

### ISSUE THREAD

**Issue by pismy** [Orange-OpenSource/Orange-Boosted-Bootstrap#190]
- Operating system and version: any
- Browser and version: any
- Reproduced on: Boosted 4.3.1
- Component: [Nav light](https://boosted.orange.com/docs/4.3/components/navs/#nav-light)
- Description: Using a Nav light, the appearance of a tab doesn't change when selected
- Cause: jQuery script makes use of the `active` CSS class while selecting a tab while Boosted implements an `o-active` CSS class
- Workaround: duplicate the Boosted `o-active` class in a `active` selector:

```css
.o-nav-light .active {
    color: #f16e00;
    border-bottom: 3px solid #f16e00;
}
```
