### ISSUE TITLE
Mattermost bot

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#293]
Since we have an internal Mattermost for Boosted, notfying the release channel with a bot would be handy.

**Comment by ffoodd** [comment]
Example workflow file, using [the Mattermost-notifiy action](https://github.com/marketplace/actions/mattermost):

```
name: Bots
on:
  push:
    branches:
      - chore/tooling
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mattermost
        uses: mattermost/action-mattermost-notify@1.0.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
```

However this requires to open a webhook from our Mattermost itself, and I can't for now.

Se [Mattermost webhook integration doc](https://docs.mattermost.com/developer/webhooks-incoming.html) for explanations.
