### ISSUE TITLE
:focus-visible css compatibility when loading polyfill

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#324]
When using focus-visible on an angular app css defined in boosted.css doesn't apply
According to https://github.com/WICG/focus-visible/issues/179 maybe it could be more Javascript agnostic to replace 
```css
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}
```
with 
```css
.js-focus-visible :focus:not([data-focus-visible-added]) {
  outline: none;
}
```
In boosted.css. That will be transparent for boosted itself but ease the integration in Angular or Vue projects
