### ISSUE TITLE
Breadcrumb links' underlined style relies on the `<main>` tag

### ISSUE THREAD

**Issue by GaetanBt** [Orange-OpenSource/Orange-Boosted-Bootstrap#372]
The current implementation requires the breadcrumb component to be placed inside the `<main>` tag in order to have the links underlined.

You can see [in the documentation]( https://boosted.orange.com/docs/4.4/components/breadcrumb/#example) that only this rule is applying : 

```css
main li a,
main li a:hover,
p a,
p a:hover {
    text-decoration: underline;
}
```
