### ISSUE TITLE
Image in carousel is not fluid anymore

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#405]
With the merge of Bootstrap's carousels and o-carousel, a property is missing:
```css
.carousel .carousel-item img {
    width: 100%
}
```

Should get this back, but preferably using `max-widht`.
