### ISSUE TITLE
Pagination - inconsistant margin

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#433]
[In documentation, the pagination component](https://boosted.orange.com/docs/4.5/components/pagination/) has custom CSS dedicated to docs: 
```css
.bd-example .pagination {
margin-top: .5rem;
margin-bottom: .5rem;
}
```
That style is not in `boosted.css`, so when a projet use pagination component, that's the default value in reboot that applies to `<ul>` element:

```css
dl, ol, ul {
    margin-top: 0;
    margin-bottom: 1rem;
}
```

So I think that pagination needs to handle default margin top and bottom to 0 or to 1 spacer but 1rem is not a coherent spacing value in boosted.
