### ISSUE TITLE
Misaligned input-group with icon

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#491]
When an input-group contains an icon, it's misaligned—because of the following rule probably:
```css
.btn [class*="icon-"]::before {
    font-size: 1.25rem;
}
```

![input-group](https://user-images.githubusercontent.com/2890570/94124658-8ed1a280-fe55-11ea-80fc-d5f905fc03e7.png)

Should check buttons with icon, too.
