### ISSUE TITLE
Focus is invisible in navbar with white background

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#56]
Either you assume black background as a default (meaning no need for `.navbar-inverse`) or you only apply a white outline when navbar is inverse.

But for now I need to override the outline by myself, using:
```css
.navbar-brand:focus,
.navbar-nav .nav-link:focus {
  outline-color: $black;
}
```
