### ISSUE TITLE
Dropdown is invisible in navbar with white background

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#57]
Almost the same that #56, but in dropdown there's another point: the caret (always in white when in navbar) stays in white as a default, making dropdown unguessable.

For now I fix it this way:

```css
.navbar .dropdown-toggle {
  &:focus {
    outline-color: $black;
  }

  &::after {
    color: $brand-primary;
    margin: 0;
  }
}
```
