### ISSUE TITLE
hover & focus aren't visible in o-footer

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#59]
Links appearance doesn't change when hovering / focusing them in Orange footer component.

The simplest way I found is:
```css
.o-footer {
  a:hover,
  a:focus {
    color: $brand-primary !important;
  }
}
```

This is very soft and might be better, but I suppose you'll find a good design ;)
