### ISSUE TITLE
[Feature] Star rating system

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#61]
I wrote a small chunk of code to make a star rating system, as accessible and simple as possible.

I based it on [Lea Verou's system](http://lea.verou.me/2011/08/accessible-star-rating-widget-with-pure-css/) which might not be the best, but as far as I tested it, it worked fine.

Take a look at the HTML:
```html
<form class="w-100 mt-1" action="/" method="get">
  <fieldset class="d-flex flex-row-reverse justify-content-center o-rating">
    <legend class="sr-only">Pertinence des résultats</legend>

    <input type="radio" id="exceptionnel" name="rating" value="5" />
    <label for="exceptionnel" class="px-0 py-0 text-nowrap h1 mb-0" data-toggle="tooltip" data-placement="bottom" title="Exceptionnel">Exceptionnel</label>

    <input type="radio" id="tres-bon" name="rating" value="4" />
    <label for="tres-bon" class="px-0 py-0 text-nowrap h1 mb-0" data-toggle="tooltip" data-placement="bottom" title="Très bon">Très bon</label>

    <input type="radio" id="moyen" name="rating" value="3" />
    <label for="moyen" class="px-0 py-0 text-nowrap h1 mb-0" data-toggle="tooltip" data-placement="bottom" title="Moyen">Moyen</label>

    <input type="radio" id="passable" name="rating" value="2" />
    <label for="passable" class="px-0 py-0 text-nowrap h1 mb-0" data-toggle="tooltip" data-placement="bottom" title="Passable">Passable</label>

    <input type="radio" id="mediocre" name="rating" value="1" />
    <label for="mediocre" class="px-0 py-0 text-nowrap h1 mb-0" data-toggle="tooltip" data-placement="bottom" title="Médiocre">Médiocre</label>
  </fieldset>
  <button type="submit" class="sr-only">Noter la pertinence</button>
</form>
```

And the associated CSS:
```css
.o-rating:not(:checked) > input {
  @extend .custom-control-input;
}

.o-rating:not(:checked) > label {
  color: $custom-control-indicator-bg;
  cursor: pointer;
  overflow: hidden;
  width: 1em;
}

.o-rating:not(:checked) > label:before {
  content: "★ ";
}

.o-rating > input:checked ~ label {
  color: $custom-control-checked-indicator-bg;
}

.o-rating:not(:checked) > label:hover,
.o-rating:not(:checked) > label:hover ~ label {
  color: $brand-warning;
}

.o-rating > input:checked + label:hover,
.o-rating > input:checked + label:hover ~ label,
.o-rating > input:checked ~ label:hover,
.o-rating > input:checked ~ label:hover ~ label,
.o-rating > label:hover ~ input:checked ~ label {
  color: $brand-info;
}
```

You may notice that:
- I'm using an image replacement technique to hide label
- I improved a bit by using a tooltip to show label, making it (I hope) clearer
- I use an unicode character for the star, but I planned to customize the project's icon-font.

@sdeschamps-orange shared [an interesting tutorial from the WAI](https://www.w3.org/WAI/tutorials/forms/custom-controls/#a-star-rating) which could be a better reference, but is pretty much the same approach for styling.

Could this be interesting for Boosted?
