### ISSUE TITLE
Customize Sass - Importing Helvetica fonts

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#758]
Considering [Customize Sass - Importing section](https://boosted.orange.com/docs/5.0/customize/sass/#importing), a Boosted user tried to do:

```scss
$breadcrumb-margin-bottom: 0rem;
$breadcrumb-divider: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 9 14' width='7' height='10'><path fill='white' d='M-.4 12l2 2 7-7-7-7-2 2 5 5z'/></svg>");

// Default theme
@import "../node_modules/boosted/scss/orange-helvetica.scss";
@import "../node_modules/boosted/scss/boosted.scss";
```

It raises an error that `.woff2` files can't be found.

This is due to the `orange-helvetica.scss` content:
```scss
$font-path: "../fonts/" !default;

@font-face {
  // [...]
  src: url("#{$font-path}HelvNeue55_W1G.woff2") format("woff2") #{"/*rtl:url('#{$font-path}HelveticaNeueW20-55Roman.woff2') format('woff2')*/"};
}
```

So, it is possible to do that:

```scss
$breadcrumb-margin-bottom: 10rem;
$breadcrumb-divider: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 9 14' width='7' height='10'><path fill='white' d='M-.4 12l2 2 7-7-7-7-2 2 5 5z'/></svg>");
$font-path: "../node_modules/boosted/dist/fonts/";

@import "../node_modules/boosted/scss/boosted";
@import "../node_modules/boosted/scss/orange-helvetica.scss";
```

In another project, they had to do `$font-path: "../dist/fonts/";`

I think this part of the documentation is not clear enough considering that we have this specificity that Bootstrap doesn't have: `orange-helvetica.scss`. This part of the documentation would deserve some precisions about it.
